# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projekte\PyAudioPlay\AudioPlay_V0\QT_GUI\diag_keyboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


