# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projekte\PyAudioPlay\AudioPlay_V0\QT_GUI\diag_keyboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogKeyboard(object):
    def setupUi(self, DialogKeyboard):
        DialogKeyboard.setObjectName("DialogKeyboard")
        DialogKeyboard.resize(640, 480)
        self.lineEditInput = QtWidgets.QLineEdit(DialogKeyboard)
        self.lineEditInput.setGeometry(QtCore.QRect(10, 10, 441, 20))
        self.lineEditInput.setObjectName("lineEditInput")
        self.pushButton = QtWidgets.QPushButton(DialogKeyboard)
        self.pushButton.setGeometry(QtCore.QRect(10, 50, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(DialogKeyboard)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 50, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(DialogKeyboard)
        self.pushButton_3.setGeometry(QtCore.QRect(580, 420, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(DialogKeyboard)
        self.pushButton_4.setGeometry(QtCore.QRect(510, 420, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(37)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(DialogKeyboard)
        QtCore.QMetaObject.connectSlotsByName(DialogKeyboard)

    def retranslateUi(self, DialogKeyboard):
        _translate = QtCore.QCoreApplication.translate
        DialogKeyboard.setWindowTitle(_translate("DialogKeyboard", "Tastatur-Eingabe"))
        self.pushButton.setText(_translate("DialogKeyboard", "A\n"
"      1"))
        self.pushButton_2.setText(_translate("DialogKeyboard", "B\n"
"      2"))
        self.pushButton_3.setText(_translate("DialogKeyboard", "r"))
        self.pushButton_4.setText(_translate("DialogKeyboard", "a"))
