# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projekte\PyAudioPlay\AudioPlay_V0\QT_GUI\form_image_V0.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormImage(object):
    def setupUi(self, FormImage):
        FormImage.setObjectName("FormImage")
        FormImage.setWindowModality(QtCore.Qt.ApplicationModal)
        FormImage.resize(800, 600)
        self.pushButtonBack = QtWidgets.QPushButton(FormImage)
        self.pushButtonBack.setGeometry(QtCore.QRect(10, 530, 60, 60))
        self.pushButtonBack.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.pushButtonNext = QtWidgets.QPushButton(FormImage)
        self.pushButtonNext.setGeometry(QtCore.QRect(80, 530, 60, 60))
        self.pushButtonNext.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonNext.setFont(font)
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.pushButtonExit = QtWidgets.QPushButton(FormImage)
        self.pushButtonExit.setGeometry(QtCore.QRect(730, 530, 60, 60))
        self.pushButtonExit.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.graphicsView = QtWidgets.QGraphicsView(FormImage)
        self.graphicsView.setGeometry(QtCore.QRect(10, 20, 781, 501))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButtonZoomN = QtWidgets.QPushButton(FormImage)
        self.pushButtonZoomN.setGeometry(QtCore.QRect(170, 530, 60, 60))
        self.pushButtonZoomN.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonZoomN.setFont(font)
        self.pushButtonZoomN.setAutoRepeat(True)
        self.pushButtonZoomN.setObjectName("pushButtonZoomN")
        self.pushButtonZoomP = QtWidgets.QPushButton(FormImage)
        self.pushButtonZoomP.setGeometry(QtCore.QRect(240, 530, 60, 60))
        self.pushButtonZoomP.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonZoomP.setFont(font)
        self.pushButtonZoomP.setAutoRepeat(True)
        self.pushButtonZoomP.setObjectName("pushButtonZoomP")

        self.retranslateUi(FormImage)
        QtCore.QMetaObject.connectSlotsByName(FormImage)

    def retranslateUi(self, FormImage):
        _translate = QtCore.QCoreApplication.translate
        FormImage.setWindowTitle(_translate("FormImage", "Cover Viewer"))
        self.pushButtonBack.setText(_translate("FormImage", "á"))
        self.pushButtonNext.setText(_translate("FormImage", "â"))
        self.pushButtonExit.setText(_translate("FormImage", "r"))
        self.pushButtonZoomN.setText(_translate("FormImage", "¹"))
        self.pushButtonZoomP.setText(_translate("FormImage", "º"))
